server:
  port: 18005
# 数据源配置
spring:
  # datasoure默认使用JDBC
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Root@123
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/zipkin?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://120.78.166.194:3306/zipkin?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  sleuth:
    enabled: false
  rabbitmq:
    host: 120.78.166.194
    port: 5672
    password: mimashishenme
    username: admin

zipkin:
  storage:
    type: mysql

logging:
  file: logs/zipkin-db.log
